name: CI/CD pipeline

# Define which action triggers the workflow
on: 
  push:

jobs:
    admin:
      runs-on: "ubuntu-latest"
      timeout-minutes: 15
      steps:  
       - name: Configuration for main branch
         if: ${{ github.ref == 'refs/heads/main' }}
         run: |
          echo "GCP_WIP=${{ secrets.MAIN_WIP }}" >> $GITHUB_ENV
          echo "GCP_SA=${{ secrets.MAIN_SA }}" >> $GITHUB_ENV

     
