name: CI/CD pipeline

# Define which action triggers the workflow
on: 
  push: 

jobs:
  auth:
    name: Authenticate to GCP
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    permissions:
      contents: read
      id-token: write 

  steps:
     # I only need to declare environment variables once at the beginning
     # The subsequent steps can access the variables by default
    - name: Configuration for main branch
      if: ${{ github.ref == 'refs/heads/main' }}
      # Side note, I can run any Linux command here, not just 'echo'
      run: |
        echo "GCP_WIP=${{ secrets.MAIN_WIP }}" >> $GITHUB_ENV
        echo "GCP_SA=${{ secrets.MAIN_SA }}" >> $GITHUB_ENV

    - name: Configuration for beta branch
      if: ${{ github.ref == 'refs/heads/beta' }}
      run: |
        echo "GCP_WIP=${{ secrets.BETA_WIP }}" >> $GITHUB_ENV
        echo "GCP_SA=${{ secrets.BETA_SA }}" >> $GITHUB_ENV

    - name: Configuration for beta branch
      if: ${{ github.ref == 'refs/heads/dev' }}
      run: |
        echo "GCP_WIP=${{ secrets.DEV_WIP }}" >> $GITHUB_ENV
        echo "GCP_SA=${{ secrets.DEV_SA }}" >> $GITHUB_ENV    

    - name: Authenticate to GCP
      if:  env.GCP_WIP != null && env.GCP_SA != null
      uses: google-github-actions/auth@v0
      with:
        workload_identity_provider: ${{ env.GCP_WIP }}
        service_account: ${{ env.GCP_SA }}
